blank_issues_enabled: true
contact_links:
  - name: General Technical Question
    about: "If you have a question like *How should I create my label times?* you can ask on StackOverflow using the #compose-ml tag."
    url: https://stackoverflow.com/questions/tagged/compose-ml
  - name: Real-time chat
    url: https://join.slack.com/t/alteryx-oss/shared_invite/zt-182tyvuxv-NzIn6eiCEf8TBziuKp0bNA
    about: "If you want to meet others in the community and chat about all things Alteryx OSS then check out our Slack."
